---
title: "compare_samples"
output: html_document
---

A script to find test exampels where a model using pre-trained embeddings and a model using polarised embeddings make different predictions

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```


```{r, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
pretrained <- read.delim('fasttext_hate_pretrained.txt', sep='\t', header = TRUE)
colnames(pretrained) <- c('tweet', 'pred_pretrained', 'gold')
custom <- read.delim('fasttext_hate_custom.txt', sep='\t', header = TRUE)
colnames(custom) <- c('tweet', 'pred_custom', 'gold')
combined <- merge(pretrained, custom)
test <- read.delim('hatetest.tsv', sep='\t', header=FALSE)
pretrained$ID <- seq.int(nrow(pretrained))
custom$ID <- seq.int(nrow(custom))
test$ID <- seq.int(nrow(test))
pretrained <- merge(pretrained, test)
combined <- merge(pretrained, custom)
combined <- combined %>%
  select(ID, V1, pred_pretrained, pred_custom, gold)
different <- combined %>%
  filter(!pred_pretrained == pred_custom)
write.table(different, file='fasttext_hate_different_preds.txt', sep='\t')
```